[workspace]
members = ["proxy", "proxy_cli", "proxy_netbench"]
resolver = "3"

[workspace.package]
version = "0.2.1"
edition = "2024"
rust-version = "1.93"

[workspace.dependencies]
apple-native-keyring-store = "0.2"
arc-swap = "1.7"
clap = "4.5"
humantime = "2.3"
jemallocator = { package = "tikv-jemallocator", version = "0.6" }
keyring-core = "0.7"
linux-keyutils-keyring-store = "0.2"
lz4_flex = "0.12"
mimalloc = { version = "0.1", default-features = false }
parking_lot = "0.12"
postcard = "1.1"
radix_trie = "0.3"
rand = "0.9"
safechain-proxy-lib = { path = "./proxy", version = "0.2.1" }
secrecy = "0.10"
semver = "1.0"
serde = "1.0"
serde_html_form = "0.4"
serde_json = "1"
serde_test = "1"
static_vcruntime = "3.0"
sudo = "0.6"
tokio = "1.48"
windows-native-keyring-store = "0.5"

[workspace.dependencies.rama]
git = "https://github.com/plabayo/rama"
rev = "03e88f1ccdf260a8c9a3be16735198855ee44f44"
