[package]
name = "safechain-proxy"
description = "MITM SafeChain HTTP(S)/SOCKS5 Proxy for Developer Security"
version = "0.1.0"
edition = "2024"
publish = false
rust-version = "1.91"
resolver = "3"

[features]
default = ["har"]
har = []

[dependencies]
clap = { version = "4.5", features = ["derive"] }
keyring-core = "0.7"
secrecy = "0.10"
tokio = { version = "1.48", features = ["full"] }
serde = "1.0"
postcard = { version = "1.1", features = ["alloc"] }

[target.'cfg(target_os = "linux")'.dependencies]
linux-keyutils-keyring-store = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
apple-native-keyring-store = { version = "0.2", features = ["keychain"] }
sudo = "0.6"

[target.'cfg(target_os = "windows")'.dependencies]
windows-native-keyring-store = "0.4"

[dependencies.rama]
git = "https://github.com/plabayo/rama"
rev = "33ffcdcd69cc1e9a73b5d1f903f84825793f2248"
features = ["http-full", "proxy-full", "dns", "boring"]

[dev-dependencies]
tracing-test = "0.2"
