[package]
name = "safechain-proxy"
description = "MITM SafeChain HTTP(S)/SOCKS5 Proxy for Developer Security"
version = "0.1.0"
edition = "2024"
publish = false
rust-version = "1.91"
resolver = "3"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
keyring-core = "0.7"
secrecy = "0.10"
tokio = { version = "1.48", features = ["full"] }
serde = "1.0"
serde_json = "1.0"

[target.'cfg(target_os = "linux")'.dependencies]
linux-keyutils-keyring-store = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
apple-native-keyring-store = { version = "0.2", features = [ "keychain" ] }
sudo = "0.6"

[target.'cfg(target_os = "windows")'.dependencies]
windows-native-keyring-store = "0.4"

[dependencies.rama]
git = "https://github.com/plabayo/rama"
rev = "755c4c96a0f8ae5a19ffd5c30a00e4099368cc95"
features = ["http-full", "proxy-full", "dns", "boring"]

[dev-dependencies]
tracing-test = "0.2"
