name: Build Unix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-unix-agent:
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: macos-14
          - arch: arm64
            runner: macos-14

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Run tests
        run: make test

      - name: Build binaries for darwin/${{ matrix.arch }}
        run: make build-darwin-${{ matrix.arch }} VERSION="${{ inputs.version || 'dev' }}"

      - name: Prepare artifacts
        run: |
          mv bin/safechain-agent-darwin-${{ matrix.arch }} safechain-agent-darwin-${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: safechain-agent-darwin-${{ matrix.arch }}
          path: |
            safechain-agent-darwin-${{ matrix.arch }}

  build-unix-proxy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: arm64
            target: aarch64-apple-darwin
            runner: macos-14
            os: darwin
          - arch: amd64
            target: x86_64-apple-darwin
            runner: macos-14
            os: darwin
          - arch: amd64
            target: x86_64-unknown-linux-musl
            runner: ubuntu-latest
            os: linux
          - arch: arm64
            target: aarch64-unknown-linux-musl
            runner: ubuntu-24.04-arm
            os: linux

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Install Zig
        if: contains(matrix.target, 'unknown-linux-musl')
        uses: mlugg/setup-zig@e7d1537c378b83b8049f65dda471d87a2f7b2df2
        with:
          version: 0.13.0

      - name: Install cargo-zigbuild
        if: contains(matrix.target, 'unknown-linux-musl')
        run: cargo install cargo-zigbuild --locked

      - name: Rust Cache
        uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5
        with:
          env-vars: "RUST_TOOLCHAIN=stable"

      - name: Build proxy binary for linux musl
        if: contains(matrix.target, 'unknown-linux-musl')
        run: cargo zigbuild --release -p safechain-proxy --target "${{ matrix.target.name }}"

      - name: Build proxy binary for ${{ matrix.os }}/${{ matrix.arch }}
        if: !(contains(matrix.target, 'unknown-linux-musl'))
        run: cargo build --release -p safechain-proxy --target ${{ matrix.target }}

      - name: Prepare artifacts
        run: |
          mv target/${{ matrix.target }}/release/safechain-proxy safechain-proxy-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: safechain-proxy-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            safechain-proxy-${{ matrix.os }}-${{ matrix.arch }}
