name: CI Checks

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  proxy-checks:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            runner: macos-14
          - target: x86_64-apple-darwin
            runner: macos-14-large
          - target: x86_64-pc-windows-msvc
            runner: windows-latest
          - target: aarch64-pc-windows-msvc
            runner: windows-11-arm
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest

    runs-on: ${{ matrix.runner }}
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          env-vars: "RUST_TOOLCHAIN=stable"
      - name: check
        run: |
          cargo check --target ${{ matrix.target }} --workspace
      - name: clippy
        run: |
          cargo clippy --target ${{ matrix.target }} --workspace
      - name: test
        run: |
          cargo test --target ${{ matrix.target }} --workspace
      - name: integration test
        run: |
          cargo test --target ${{ matrix.target }} --workspace -- --ignored
