name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

  build-unix:
    needs: extract-version
    uses: ./.github/workflows/build-macos-pkg.yml
    with:
      version: ${{ needs.extract-version.outputs.version }}
    secrets: inherit

  build-windows:
    needs: extract-version
    uses: ./.github/workflows/build-windows.yml
    with:
      version: ${{ needs.extract-version.outputs.version }}
    secrets: inherit

  release:
    needs: [extract-version, build-unix, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release files
        id: checksums
        run: |
          mv artifacts/safechain-ultimate-darwin-amd64/safechain-ultimate-darwin-amd64 .
          mv artifacts/safechain-ultimate-darwin-arm64/safechain-ultimate-darwin-arm64 .

          mv artifacts/safechain-proxy-darwin-amd64/safechain-proxy-darwin-amd64 .
          mv artifacts/safechain-proxy-darwin-arm64/safechain-proxy-darwin-arm64 .

          mv artifacts/safechain-proxy-linux-amd64/safechain-proxy-linux-amd64 .
          mv artifacts/safechain-proxy-linux-arm64/safechain-proxy-linux-arm64 .

          mv artifacts/SafeChainUltimate.amd64.msi/SafeChainUltimate.amd64.msi ./SafeChainUltimate-windows-amd64.msi
          mv artifacts/SafeChainUltimate.arm64.msi/SafeChainUltimate.arm64.msi ./SafeChainUltimate-windows-arm64.msi

          mv artifacts/SafeChainUltimate-amd64.pkg/SafeChainUltimate-amd64.pkg ./SafeChainUltimate-darwin-amd64.pkg
          mv artifacts/SafeChainUltimate-arm64.pkg/SafeChainUltimate-arm64.pkg ./SafeChainUltimate-darwin-arm64.pkg

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            safechain-ultimate-darwin-amd64
            safechain-ultimate-darwin-arm64
            safechain-ultimate-ui-darwin-amd64
            safechain-ultimate-ui-darwin-arm64
            safechain-proxy-darwin-amd64
            safechain-proxy-darwin-arm64
            safechain-proxy-linux-amd64
            safechain-proxy-linux-arm64
            SafeChainUltimate-windows-amd64.msi
            SafeChainUltimate-windows-arm64.msi
            SafeChainUltimate-darwin-amd64.pkg
            SafeChainUltimate-darwin-arm64.pkg

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
